### ISSUE TITLE
No release made for over 1.5 years

### ISSUE THREAD

**Issue by sava-nicolae-dragos** [dotnet/Docker.DotNet#418]
Some of the changes made are quite useful, but no release has been made in the last 1.5 years.
A new release will be welcomed.

**Comment by hanslai** [comment]
I wonder if this repository is still being maintained.  lots of Issues over a year or two is still not closed.

**Comment by galvesribeiro** [comment]
Folks I'm not from MSFT but I'm one of the contributors of this repo so I can speak a bit about it... 

As far as I know, since the beginning, the release cadence on this repo is probably not as fast as Docker APIs evolve and as community would probably expect it to. There are multiple things that are probably hold on releases and the new things from .Net world that can be used to enhance its performance and usability. For example, the new `Memory<T>`/`Span<T>` could be used on the streams and enhance performance but, IIRC, it is not compatible with .Net 4.5 which would make a nightmare to maintain this repo to support multi-targeting.

The major reason I see, is that this library is used by many MSFT products that are on older .Net versions (even 2.0 I believe) and there are 3rd party customers that are using that old (and unsupported) tech yet hence why merging and releasing new stuff takes a lot while.

@jterry75 can give the final word on that, but if this is  something that is blocking this widely used library to move forward, perhaps it is time to start a new repo, outside MSFT structure, and fork/port/migrate this codebase there to release new packages. 

I could speak with .Net Foundation guys as I'm a member there and see if this could be a project that should be added under `dotnet/*` organisation so it can move faster and leverage all .Net community to push it forward...

Just my 2c here...

**Comment by TrojanOlx** [comment]
@galvesribeiro Thanks a lot for answering this.  Would love to see this repository in .Net Core.

**Comment by sandersaares** [comment]
This project is valuable to me and I would be happy to use and contribute to a fork that is actively maintained.

**Comment by jterry75** [comment]
@sandersaares - I no longer have the time to contribute to this project but if you would like to send PR's and @mention me I can get them in. As @galvesribeiro mentioned above it may be easier to move this out of `Microsoft/*`. There are new requirements for repos under `Microsoft/*` and this project no longer meets requirements to push to nuget due to code signing and compliance.

**Comment by galvesribeiro** [comment]
Ok, I'll try to get in touch with @jongalloway and other folks from .Net Foundation to see how can we proceed with it. 

This is a very important library for the .Net Ecosystem and I believe we can move forward with it outside MSFT.

Most likely we will end up rewriting/porting it to latest `netstandard2.x` and make it available on the Foundation. Use the codebase _as is_, perhaps may imply on some legal issues that requires MSFT legal team to _"donate"_  the project to the Foundation, so I guess rewriting it on a new project UNDER the Foundation would be the fastest way moving forward...

@jongalloway / @terrajobst what do you guys think?

**Comment by jterry75** [comment]
@galvesribeiro - If we can get it under dotnet/ I am sure we can do the right legal work on our end (famous last words :) ). And yes it needs some serious updates to `netstandard2.x` and should likely drop support for older clients

**Comment by jongalloway** [comment]
Adding @onovotny since he's taking over as .NET Foundation executive director.

The new project application is here: https://github.com/dotnet-foundation/projects/issues/new/choose

As a Microsoft contributed project, there are some special hoops to jump through. If I can get an e-mail address, I can send that form over.

It's not necessary for the repository to move into the dotnet org, although not a bad idea.

**Comment by galvesribeiro** [comment]
>  If we can get it under dotnet/ I am sure we can do the right legal work on our end (famous last words :) ). And yes it needs some serious updates to netstandard2.x and should likely drop support for older clients

@jterry75 yeah, we would put that efforts after the _donation_ and legal part. I think if .Net team doesn't support the older clients, this shouldn't as well, but that is something for the future. 

@jongalloway thanks! You can ping @jterry75 internally I think. Hi @onovotny! Wellcome! 😄 

My email is _"gutemberg -et- outlook -dot- com"_ and I could lead this migration/revamp on the new repo so feel free to email me.

 > It's not necessary for the repository to move into the dotnet org, although not a bad idea.

Yeah I know. I just think it would be good for visibility sake to have it there and to make it clear that it is not _owned_ by a single person.

Let me know if I can help with anything on it.

Thanks!

**Comment by jongalloway** [comment]
I've emailed @jterry75 cc @onovotny.

**Comment by galvesribeiro** [comment]
Yo folks! News on that matter?

**Comment by jterry75** [comment]
@galvesribeiro - We are discussing internally. Hope to know more soon

**Comment by galvesribeiro** [comment]
Cool, thanks! Looking forward to hear from you!

**Comment by worldbeater** [comment]
Writing here to say thanks to maintainers for all the efforts. 
Looking forward for an update on NuGet.

**Comment by cfauchere** [comment]
+1 on this new release is needed :)

**Comment by AlonAm** [comment]
+1 for new release

**Comment by cfauchere** [comment]
What is preventing a new release? Can I help? @jterry75

**Comment by jterry75** [comment]
I wish we could. The requirements for MS NuGet packages require MS signed releases at the moment and this does not meet the requirements for that to happen. So your best bet is to build/sign/package according to your applications needs. Apologies for any inconvenience.

**Comment by galvesribeiro** [comment]
@jterry75 any updates on the "donation" process to .Net Foundation?

**Comment by jterry75** [comment]
> @jterry75 any updates on the "donation" process to .Net Foundation?

I will ping the thread again

**Comment by jterry75** [comment]
@galvesribeiro - https://github.com/dotnet-foundation/projects/issues/52. Mind updating that thread with what you think the proposed governance model should be. Thanks!

**Comment by galvesribeiro** [comment]
Done! :shipit:

**Comment by jterry75** [comment]
Thank you!

**Comment by jhenkens** [comment]
Seems the foundation ticket was closed in a matter that seemed this is resolved. Is there forward progress on that since April?

**Comment by galvesribeiro** [comment]
Hello @jhenkens 

We just got the sign certificates this week. I'll make the process to update the repo this Weekend so we can sign the binaries and will be able to set it free to nuget! :) Bear with me!

**Comment by yogkul** [comment]
Any update on pushing new nuget package?

**Comment by galvesribeiro** [comment]
Yo folks! Again, sorry for all the delay.

The sign configuration is implemented on this PR: https://github.com/dotnet/Docker.DotNet/pull/454

If anyone want to follow that up or review please feel free.

After that gets merged, we will move forward with the releases.

Again, thanks for wait, I appreciate that.

**Comment by galvesribeiro** [comment]
Hey folks! Glad to say the after so much time we have a release :)

I hope we can get on track to working on it and having faster shipping from now on.

Thank you all for being patient!
