### ISSUE TITLE
When will nugget release a new version？

### ISSUE THREAD

**Issue by DarrenWen** [dotnet/Docker.DotNet#442]
I found that I have fixed a lot of bugs in the last six months, but nuget is still the version used six months ago. Do the bloggers have plans to release a new version of nuget recently?

**Comment by galvesribeiro** [comment]
Hey @DarrenWen thanks for the contributions.

As you may see, we've moved the project to .Net Foundation. With that said, we're in the onboarding process which means some things need to be setup in order for us to create proper NuGet.

Due to all this pandemic mess, most of us are dealing with some issues and the things slowed down.

Keep an eye on https://github.com/dotnet/Docker.DotNet/issues/443 for updates and bear with me that we will have a release soon enough.

Again, thanks for all the contributions!
