### ISSUE TITLE
Maintenance of the project

### ISSUE THREAD

**Issue by HofmeisterAn** [dotnet/Docker.DotNet#568]
@jterry75 @galvesribeiro How can we maintain the maintenance and further development for Docker.DotNet? It would be a pity if all the work is not continued. There are a couple of pull requests waiting for approval, and the latest Docker Desktop ~~for Windows~~ version (4.10.0) does not work well with version 3.125.5. It has the same issue mentioned here: https://github.com/dotnet/Docker.DotNet/issues/554#issuecomment-1170444866.

**Comment by galvesribeiro** [comment]
Hello @HofmeisterAn.

I've mentioned here on multiple issues, on slack and on Discord. The way the project is built is really hard to maintain since it depends on a Go-based codegen. I've started working on a Roslyn based code-generator which instead of rely on Go it read the models using Docker YAML API file, usage of Pipelines instead of relying on streams, etc. 

Unfortunately docker YAML schema doesn't follow a well-structured YAML file definition, which breaks every single parser I've saw so far including ones from MSFT and Yaml.Net and I wasn't able to find time yet to finish/fix it and as mentioned before the current version is only receiving bug fixes when they are blockers without workaround as it seems to be the case on #554 and I replied there.

Contributions are more them welcome. I'd like to keep going with the refactor but both the YAML or JSON definitions from Docker APIs are a big mess and it would be unbearable to keep using Go files.

I'll open another issue that explains what I was planning and see if anyone has a good idea of what could we do to get those specs supported.

**Comment by HofmeisterAn** [comment]
Sounds like a challenging and fun task, TBH 😅. I'm happy to help as much as I can. Maybe we can work together on the Roslyn part or split it into smaller chunks. I think it's just important to continuously improve and maintain `Docker.DotNet` a lot of devs depend on it.

**Comment by galvesribeiro** [comment]
The Roslyn part is quite easy. I have it mostly done. Like I said the major efforts would be to replace the "source" of the model which today is the Go files and my idea would be to use their API schemas. I'll keep looking. If you have any suggestions on that area it would be great! Thanks

**Comment by HofmeisterAn** [comment]
If you like to share your work within the new issue or somehow else, I can start to take a look at it. If you know already some specific tasks, just reach out. I can start working on them.

**Comment by SeanFarrow** [comment]
@galvesribeiro 
I'm also happy to help whee I can.
It wouldalso be really nice to have a sub-library to interrogate the insallation status of docker in a cross-patform manner.

**Comment by HofmeisterAn** [comment]
Hi 👋 @galvesribeiro, Docker.DotNet is one important upstream dependency for Testcontainers for .NET. As OSS maintainers, contributors and users of Docker.DotNet we would like to support with day to day maintenance, bug fixes and upcoming features.

We would like to become strong maintainers and support this project much more. It would be great to have a chat with you (or other core maintainers) about a collaboration.

Please let us know if you are interested and how we get in touch with each other or just ping me on [Slack](https://slack.testcontainers.org/) (/cc @kiview).

**Comment by galvesribeiro** [comment]
Hey! Lets talk. I’ll ping you over this week.

THanks!

On Nov 3, 2022, at 2:06 PM, Andre Hofmeister ***@***.***> wrote:



Hi 👋 @galvesribeiro<https://github.com/galvesribeiro>, Docker.DotNet is one important upstream dependency for Testcontainers for .NET. As OSS maintainers, contributors and users of Docker.DotNet we would like to support with day to day maintenance, bug fixes and upcoming features.

We would like to become strong maintainers and support this project much more. It would be great to have a chat with you (or other core maintainers) about a collaboration.

Please let us know if you are interested and how we get in touch with each other or just ping me on Slack<https://slack.testcontainers.org/> (/cc @kiview<https://github.com/kiview>).

**Comment by HofmeisterAn** [comment]
@galvesribeiro Do you have time for a quick chat this week? What about Wednesday >= 15:00 CET?

**Comment by galvesribeiro** [comment]
Hey @HofmeisterAn I was OOO. Can you ping me on slack? I use the same alias as on GH. Thanks

**Comment by HofmeisterAn** [comment]
@galvesribeiro Did you join the Testcontainers Slack workspace? Or which Slack workspace are you talking about? I am not member of the .NET Foundation Slack workspace (not sure if one exists), but it looks like it is not public. Nor I am a member of the .NET Foundation, never [membership application](https://dotnetfoundation.org/membership/become-a-member).

**Comment by galvesribeiro** [comment]
There is a public .net slack.

**Comment by HofmeisterAn** [comment]
What's the Workspace?

**Comment by galvesribeiro** [comment]
Now that we are finally in touch (I'm sorry I haven't match your account here with your Slack, silly me) and we have the release, I'll close this issue and will drive this convo on Slack with you guys. 

Thanks
