### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by soroshsabz** [dotnet/Docker.DotNet#677]
ITNOA

Thanks lot for all works and contributions

I want to use this library, but as I see last Merge for more than 9 month ago

and some PR still pending for months

So I have a question, what is roadmap of this library? is this library still active under development or not? how many collaborator exist for this library? what is plan for future of this project?

Thanks again for great working

**Comment by galvesribeiro** [comment]
Hello,

Thanks for the reply. Yes it is. I've a new branch which I'm working on a complete revamp of the current codebase to modernize it and avoid using the Go code in favor of a source generator based in Roslyn.

You will see more updates soon.

Thanks!

**Comment by soroshsabz** [comment]
It is good news

thanks

**Comment by soroshsabz** [comment]
@galvesribeiro  and one little another question, did you have any plan to support docker swarm and docker compose too?

thanks a lot

**Comment by galvesribeiro** [comment]
It will get piece by piece. First with the core Docker API which is what I'm working here. Then, since the foundation will already be there, add Swarm and Compose will be easy so yeah, we can add those.

I'm not 100% sure it is widely used nowadays after we have Kubernetes but nothing stop we add it. I'll probably add a new package for each API, like Docker.Dotnet.Swarm/Compose or something like that.

**Comment by galvesribeiro** [comment]
@etherealbacon what are the updates that are blocking .Net 8? We can fix them and release it while I'm working on the revamp. Please let me know exactly what is going on since I see people duplicating issues for the same problem and spamming others that are no relation when in the majority of the cases they find out that they made a mistake and It got back to work.

I wasn't aware it wasn't working on .Net 8 but we can for sure release a new version with a fix as it is a major blocker not an usability/enhancement on the old codebase.

**Comment by soroshsabz** [comment]
I think maybe more collaborator can help to achieve more velocity

**Comment by ghost** [comment]
@galvesribeiro When is a new release planned? Thanks in advance, your work is much appreciated.

**Comment by bar10dr** [comment]
Love the project, looking forward to the new version.
